/**
 * Centralized error codes for the API. Use these instead of string-matching
 * error messages — wording can change, codes are stable.
 *
 * Naming: SUBJECT_PROBLEM (e.g. SPACE_NOT_FOUND, BOOKING_CAPACITY_FULL).
 */
export const ErrorCode = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  // OTP
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_BANNED: 'USER_BANNED',

  // Spaces
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  SPACE_NOT_OWNED: 'SPACE_NOT_OWNED',
  SPACE_HAS_ACTIVE_BOOKINGS: 'SPACE_HAS_ACTIVE_BOOKINGS',
  SPACE_NOT_AVAILABLE: 'SPACE_NOT_AVAILABLE',
  SPACE_HOURLY_RATE_OUT_OF_RANGE: 'SPACE_HOURLY_RATE_OUT_OF_RANGE',
  SPACE_WEEKDAYS_ONLY: 'SPACE_WEEKDAYS_ONLY',

  // Vehicles
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  VEHICLE_NOT_OWNED: 'VEHICLE_NOT_OWNED',

  // Bookings
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_STATE: 'BOOKING_INVALID_STATE',
  BOOKING_CAPACITY_FULL: 'BOOKING_CAPACITY_FULL',
  BOOKING_SELF_OWNER: 'BOOKING_SELF_OWNER',
  BOOKING_NOT_ACTIVE: 'BOOKING_NOT_ACTIVE',
  BOOKING_ALREADY_COMPLETED: 'BOOKING_ALREADY_COMPLETED',

  // Abuse / moderation
  ABUSE_REPORT_NOT_FOUND: 'ABUSE_REPORT_NOT_FOUND',
  ABUSE_INVALID_ACTION: 'ABUSE_INVALID_ACTION',
  ABUSE_SELF_REPORT: 'ABUSE_SELF_REPORT',

  // Documents
  DOC_NOT_FOUND: 'DOC_NOT_FOUND',
  DOC_INVALID_ACTION: 'DOC_INVALID_ACTION',
  DOC_UPLOAD_FAILED: 'DOC_UPLOAD_FAILED',

  // Transactions / Billing
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  REFUND_FAILED: 'REFUND_FAILED',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
