import { StyleSheet } from 'react-native';
import { Colors, FontSize, FontWeight, BorderRadius, Spacing, ExtendedColors } from '../../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.screenBg,
  },
  content: {
    padding: Spacing['3xl'],
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planCard: {
    paddingHorizontal: Spacing.screenH,
    paddingVertical: Spacing['3xl'],
    borderRadius: BorderRadius.circleXl,
    marginBottom: Spacing['4xl'],
  },
  planBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: Spacing.md,
  },
  planBadgeText: {
    color: Colors.amber,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    letterSpacing: 1,
  },
  planName: {
    fontSize: FontSize['4xl'],
    fontWeight: FontWeight.extrabold,
    color: Colors.white,
    letterSpacing: -0.5,
  },
  planPrice: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.bold,
    color: Colors.white,
    marginTop: Spacing.micro,
  },
  planPeriod: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.normal,
    color: Colors.textMuted,
  },
  planDivider: {
    height: 1,
    backgroundColor: ExtendedColors.whiteAlpha10,
    marginVertical: Spacing.xl,
  },
  planFooter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planFooterItem: {
    flex: 1,
  },
  planFooterLabel: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    marginBottom: Spacing.xs,
  },
  planFooterValue: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  planFooterDivider: {
    width: 1,
    height: 28,
    backgroundColor: ExtendedColors.whiteAlpha10,
    marginHorizontal: Spacing['3xl'],
  },
  usageBlock: {
    marginTop: Spacing.xl,
    paddingTop: Spacing.xl,
    borderTopWidth: 1,
    borderTopColor: ExtendedColors.whiteAlpha10,
  },
  usageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  usageLabel: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
  },
  usageValue: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  usageBarTrack: {
    height: 6,
    borderRadius: BorderRadius.indicator,
    backgroundColor: ExtendedColors.whiteAlpha20,
    overflow: 'hidden',
  },
  usageBarFill: {
    height: '100%',
    borderRadius: BorderRadius.indicator,
    backgroundColor: Colors.amber,
  },
  usageBarFillUnlimited: {
    backgroundColor: ExtendedColors.whiteAlpha40,
  },
  usageExpiry: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    marginTop: Spacing.sm,
    fontWeight: FontWeight.medium,
  },
  usageExpiryExpired: {
    color: Colors.errorAlt,
    fontWeight: FontWeight.bold,
  },
  activeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: BorderRadius.indicator,
    backgroundColor: Colors.successAlt,
  },
  inactiveDot: {
    backgroundColor: Colors.errorAlt,
  },
  activeBadgeText: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: Colors.successAlt,
  },
  inactiveBadgeText: {
    color: Colors.errorAlt,
  },
  sectionTitle: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: Spacing.lg,
  },
  featuresCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: Spacing['4xl'],
    overflow: 'hidden',
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
    paddingVertical: 13,
    paddingHorizontal: Spacing['3xl'],
  },
  featureRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBg,
  },
  featureText: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    color: Colors.textPrimary,
  },
  choosePlanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xl,
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.button,
    paddingVertical: Spacing['2xl'],
    marginBottom: Spacing['4xl'],
  },
  choosePlanButtonText: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.lg,
    backgroundColor: Colors.warningBg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.warning,
    paddingVertical: Spacing['2xl'],
    paddingHorizontal: Spacing['3xl'],
    marginBottom: Spacing['4xl'],
    marginTop: -Spacing.lg,
  },
  infoBannerText: {
    flex: 1,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: Colors.textPrimary,
    lineHeight: 18,
  },
  actionsCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: Spacing['4xl'],
    overflow: 'hidden',
  },
  actionRowDisabled: {
    opacity: 0.7,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing['2xl'],
    paddingHorizontal: Spacing['3xl'],
    gap: Spacing.xl,
  },
  actionIconWrapper: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionInfo: {
    flex: 1,
  },
  actionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: Spacing.micro,
  },
  actionSub: {
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
  },
  billingCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  billingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing['2xl'],
    paddingHorizontal: Spacing['3xl'],
  },
  billingInfo: {},
  billingDate: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: Colors.textPrimary,
    marginBottom: Spacing.micro,
  },
  billingId: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
  },
  billingRight: {
    alignItems: 'flex-end',
    gap: Spacing.xs,
  },
  billingAmount: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extrabold,
    color: Colors.textPrimary,
  },
  paidBadge: {
    backgroundColor: Colors.successBgAlt,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.micro,
    borderRadius: BorderRadius.badge,
  },
  paidBadgeText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: ExtendedColors.teal,
  },
  pendingBadge: {
    backgroundColor: Colors.warningBg,
  },
  pendingBadgeText: {
    color: Colors.warning,
  },
  divider: {
    height: 1,
    backgroundColor: Colors.surfaceBg,
  },
  billingHint: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
    marginTop: -Spacing.sm,
    marginBottom: Spacing.lg,
  },
  billingReceiptIcon: {
    marginLeft: Spacing.lg,
  },
  viewAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing['2xl'],
  },
  viewAllText: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.primary,
  },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xl,
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingVertical: Spacing['2xl'],
    paddingHorizontal: Spacing['3xl'],
    marginTop: Spacing['4xl'],
  },
  // ── Shared modal overlay ──
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Spacing.screenH,
  },
  // ── Receipt modal ──
  modalCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.circleXl,
    width: '100%',
    maxHeight: '85%',
    overflow: 'hidden',
  },
  receiptHeader: {
    backgroundColor: Colors.textPrimary,
    paddingVertical: Spacing['3xl'],
    alignItems: 'center',
  },
  receiptBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  receiptBrand: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.extrabold,
    color: Colors.white,
    letterSpacing: -0.5,
  },
  receiptSubhead: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
    marginTop: Spacing.xs,
    fontWeight: FontWeight.medium,
  },
  receiptBody: {
    paddingHorizontal: Spacing.screenH,
    paddingVertical: Spacing['3xl'],
  },
  receiptAmountBlock: {
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing['2xl'],
  },
  receiptAmountLabel: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
    fontWeight: FontWeight.medium,
  },
  receiptAmount: {
    fontSize: FontSize['5xl'],
    fontWeight: FontWeight.extrabold,
    color: Colors.textPrimary,
    letterSpacing: -0.5,
  },
  receiptDivider: {
    height: 1,
    backgroundColor: Colors.surfaceBg,
    marginBottom: Spacing.lg,
  },
  receiptRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingVertical: Spacing.lg,
    gap: Spacing.xl,
  },
  receiptRowLabel: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    flexShrink: 0,
  },
  receiptRowValue: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
    textAlign: 'right',
  },
  receiptRowValueWrap: {
    flex: 1,
  },
  receiptFooterNote: {
    fontSize: FontSize.xs,
    color: Colors.textMuted,
    textAlign: 'center',
    marginTop: Spacing['2xl'],
    lineHeight: 16,
  },
  receiptDoneBtn: {
    backgroundColor: Colors.primary,
    paddingVertical: Spacing['2xl'],
    alignItems: 'center',
    marginHorizontal: Spacing.screenH,
    marginBottom: Spacing.screenH,
    borderRadius: BorderRadius.button,
  },
  receiptDoneBtnText: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  // ── Help modal ──
  helpCard: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.circleXl,
    width: '100%',
    maxHeight: '80%',
    overflow: 'hidden',
  },
  helpHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.screenH,
    paddingVertical: Spacing['3xl'],
    borderBottomWidth: 1,
    borderBottomColor: Colors.surfaceBg,
  },
  helpHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
  },
  helpHeaderTitle: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
  },
  helpCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpScroll: {
    flexGrow: 0,
  },
  helpScrollContent: {
    paddingHorizontal: Spacing.screenH,
    paddingVertical: Spacing['2xl'],
  },
  helpItem: {
    marginBottom: Spacing['3xl'],
  },
  helpQuestion: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  helpAnswer: {
    fontSize: FontSize.base,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
});

