import { StyleSheet } from 'react-native';
import { ColorsType, FontSize, FontWeight, BorderRadius, Spacing, ExtendedColors } from '../../theme';

export const makeOwnerDashboardStyles = (colors: ColorsType) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  container: {
    flex: 1,
    backgroundColor: colors.screenBg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.screenBg,
  },
  scrollContent: {
    paddingHorizontal: Spacing['3xl'],
    paddingTop: Spacing['3xl'],
    paddingBottom: Spacing['7xl'],
  },
  lockBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.errorBg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.error,
    padding: Spacing.xl,
    marginBottom: Spacing.xl,
  },
  lockBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.lg,
  },
  lockBannerBody: {
    flex: 1,
    marginRight: Spacing.md,
  },
  lockBannerTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: colors.error,
    marginBottom: 2,
  },
  lockBannerText: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  lockBannerBtn: {
    backgroundColor: colors.error,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.input,
  },
  lockBannerBtnText: {
    color: colors.white,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.sm,
  },
  upiBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primaryBg,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: Spacing.xl,
    marginBottom: Spacing.xl,
  },
  upiBannerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.lg,
  },
  upiBannerBody: { flex: 1, marginRight: Spacing.md },
  upiBannerTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: colors.primary,
    marginBottom: 2,
  },
  upiBannerText: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  heroBanner: {
    borderRadius: BorderRadius.circleXl,
    padding: Spacing.screenH,
    marginBottom: Spacing['4xl'],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  heroBadgeText: {
    color: colors.amber,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.extrabold,
    letterSpacing: 1,
  },
  heroTitle: {
    fontSize: FontSize['3xl'],
    fontWeight: FontWeight.extrabold,
    color: colors.white,
    marginBottom: Spacing.xs,
  },
  heroSubtitle: {
    fontSize: FontSize.base,
    color: colors.borderMuted,
    fontWeight: FontWeight.medium,
  },
  heroBtn: {
    backgroundColor: colors.white,
    paddingHorizontal: Spacing['2xl'],
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.input,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  heroBtnText: {
    color: colors.textPrimary,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.sm,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  statCard: {
    width: '48%',
    backgroundColor: colors.white,
    borderRadius: BorderRadius.button,
    padding: Spacing.xl,
    marginBottom: Spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.textMuted,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
  },
  statIconWrapper: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.lg,
  },
  statTextBlock: {
    flex: 1,
  },
  statValue: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.extrabold,
    color: colors.textPrimary,
    marginBottom: 1,
  },
  statLabel: {
    fontSize: FontSize.xs,
    color: colors.textSecondary,
    fontWeight: FontWeight.semibold,
  },
  section: {
    marginBottom: Spacing['4xl'],
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.xl,
  },
  sectionTitle: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.extrabold,
    color: colors.textPrimary,
  },
  sectionLink: {
    fontSize: FontSize.base,
    color: colors.primary,
    fontWeight: FontWeight.semibold,
  },
  actionCard: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing['3xl'],
    marginBottom: Spacing.xl,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
    shadowColor: colors.textMuted,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  actionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.xl,
  },
  avatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.lg,
    overflow: 'hidden',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  avatarText: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: colors.textSecondary,
  },
  actionCardInfo: {
    flex: 1,
  },
  actionCardName: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    marginBottom: Spacing.micro,
  },
  actionCardDetails: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    fontWeight: FontWeight.medium,
  },
  urgentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningBgAlt,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.input,
  },
  urgentBadgeRed: { backgroundColor: colors.errorBg },
  urgentBadgeText: {
    color: colors.warning,
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
  },
  urgentBadgeTextRed: { color: colors.error },
  actionCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.surfaceBg,
    paddingTop: Spacing.xl,
  },
  actionCardDuration: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    fontWeight: FontWeight.semibold,
  },
  reviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.input,
  },
  reviewBtnText: {
    color: colors.white,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.sm,
    marginRight: Spacing.xs,
  },
  recentReqCard: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: colors.white, borderRadius: BorderRadius.button, padding: Spacing.xl, marginBottom: Spacing.md,
    borderWidth: 1, borderColor: colors.surfaceBg,
  },
  recentReqAvatar: {
    width: 38, height: 38, borderRadius: BorderRadius.circle, backgroundColor: colors.surfaceBg,
    alignItems: 'center', justifyContent: 'center', marginRight: Spacing.xl, overflow: 'hidden',
  },
  recentReqAvatarImg: { width: '100%', height: '100%', borderRadius: BorderRadius.circle },
  recentReqAvatarText: { fontSize: FontSize.lg, fontWeight: FontWeight.bold, color: colors.textSecondary },
  recentReqInfo: { flex: 1 },
  recentReqName: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: colors.textPrimary },
  recentReqSpace: { fontSize: FontSize.sm, color: colors.textMuted, marginTop: Spacing.micro },
  recentReqRight: { alignItems: 'flex-end', gap: Spacing.xs },
  recentReqBadge: { paddingHorizontal: Spacing.md, paddingVertical: 3, borderRadius: BorderRadius.sm },
  recentReqBadgeText: { fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  recentReqTime: { fontSize: FontSize.xs, color: colors.textMuted },
  liveSessionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing['2xl'],
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
    shadowColor: colors.textMuted,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  liveStatusIndicator: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.successBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.lg,
  },
  liveDot: {
    width: 12,
    height: 12,
    borderRadius: BorderRadius.badge,
    backgroundColor: colors.success,
  },
  liveSessionInfo: {
    flex: 1,
  },
  liveSessionName: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    marginBottom: Spacing.micro,
  },
  liveSessionSpace: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    fontWeight: FontWeight.medium,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.screenBg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.input,
  },
  timerText: {
    color: colors.success,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.base,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 0,
    paddingBottom: Spacing.screenH,
    paddingHorizontal: Spacing.screenH,
    marginTop: -16,
  },
  emptyStateTitle: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    marginTop: Spacing.screenH,
    marginBottom: Spacing.md,
  },
  emptyStateDesc: {
    fontSize: FontSize.md,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: Spacing.screenH,
  },
  emptyStateBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: Spacing['4xl'],
    paddingVertical: Spacing.xl,
    borderRadius: BorderRadius.md,
  },
  emptyStateBtnText: {
    color: colors.white,
    fontSize: FontSize.lg,
    fontWeight: FontWeight.semibold,
  },
  modalOverlay: {
    flex: 1, backgroundColor: ExtendedColors.overlayHeavy,
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: colors.white, borderTopLeftRadius: BorderRadius.xl, borderTopRightRadius: BorderRadius.xl,
    paddingHorizontal: Spacing.screenH, paddingTop: Spacing.screenH, paddingBottom: Spacing['6xl'],
    gap: Spacing.xl,
  },
  modalHeader: { alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.xs },
  modalIconWrap: {
    width: 64, height: 64, borderRadius: 32,
    alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.xs,
  },
  modalTitle: { fontSize: FontSize['3xl'], fontWeight: FontWeight.extrabold, color: colors.textPrimary, textAlign: 'center' },
  modalSub: { fontSize: FontSize.base, color: colors.textSecondary, textAlign: 'center', lineHeight: 20 },
  modalDetails: {
    backgroundColor: colors.screenBg, borderRadius: BorderRadius.button,
    paddingHorizontal: Spacing['2xl'], paddingVertical: Spacing.sm,
  },
  modalDetailRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingVertical: Spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  modalDetailLabel: { fontSize: FontSize.sm, color: colors.textSecondary, fontWeight: FontWeight.medium, flex: 1 },
  modalDetailValue: { fontSize: FontSize.base, color: colors.textPrimary, fontWeight: FontWeight.semibold, textAlign: 'right', flex: 1.5 },
  reasonBox: {
    backgroundColor: colors.pendingBg, borderRadius: BorderRadius.md, padding: Spacing['2xl'],
    borderLeftWidth: 3, borderLeftColor: ExtendedColors.orange,
  },
  reasonTitle: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: ExtendedColors.redOrange, marginBottom: Spacing.sm },
  reasonItem: { fontSize: FontSize.sm, color: ExtendedColors.warningAmber, lineHeight: 20 },
  modalCloseBtn: {
    paddingVertical: Spacing['2xl'], borderRadius: BorderRadius.md,
    backgroundColor: colors.surfaceBg, alignItems: 'center', marginTop: Spacing.md,
  },
  modalCloseBtnText: { fontSize: FontSize.lg, fontWeight: FontWeight.bold, color: colors.textPrimary },
});
