import { StyleSheet } from 'react-native';
import { ColorsType, FontSize, FontWeight, BorderRadius, Spacing, ExtendedColors } from '../../theme';

export const makeActiveSessionStyles = (colors: ColorsType) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.white },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  errorText: { color: colors.error, marginBottom: Spacing.xl },
  errorTextSmall: { color: colors.error, marginTop: Spacing.lg, textAlign: 'center' },
  content: { flex: 1, padding: Spacing.screenH, backgroundColor: colors.screenBg },
  stepperCard: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: Spacing.xl,
  },
  factsCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.xl,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: Spacing.xl,
  },
  factItem: { flex: 1, alignItems: 'center', paddingHorizontal: Spacing.sm },
  factLabel: { fontSize: FontSize.micro, fontWeight: FontWeight.bold, color: colors.textMuted, letterSpacing: 0.4, marginBottom: 3 },
  factValue: { fontSize: FontSize.base, fontWeight: FontWeight.bold, color: colors.textPrimary },
  factDivider: { width: 1, backgroundColor: colors.surfaceBg },
  card: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    padding: Spacing.screenH,
    borderWidth: 1,
    borderColor: colors.border,
  },
  warningHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginBottom: Spacing.xl },
  warningTitle: { color: colors.warning, fontSize: FontSize.xl, fontWeight: FontWeight.bold },
  okBadge: {
    flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', gap: Spacing.sm,
    backgroundColor: colors.successBg, borderWidth: 1, borderColor: colors.success,
    borderRadius: BorderRadius.circleXl, paddingHorizontal: Spacing.xl, paddingVertical: Spacing.sm,
    marginBottom: Spacing.xl,
  },
  okBadgeText: { color: colors.success, fontSize: FontSize.md, fontWeight: FontWeight.bold },
  cardBody: { color: colors.textBody, fontSize: FontSize.md, lineHeight: 20, marginBottom: Spacing['3xl'] },
  conditionHeading: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: Spacing.lg },
  reviewRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, backgroundColor: colors.primaryBg, borderRadius: BorderRadius.md, padding: Spacing.xl, marginTop: Spacing.xs },
  reviewRowText: { flex: 1, fontSize: FontSize.base, color: colors.textBody, fontWeight: FontWeight.medium, lineHeight: 18 },
  mediaStrip: { flexDirection: 'row', marginTop: Spacing.lg },
  thumb: { width: 100, height: 100, borderRadius: BorderRadius.sm, marginRight: Spacing.lg, backgroundColor: colors.surfaceBg },

  otpTitle: { fontSize: FontSize['3xl'], fontWeight: FontWeight.extrabold, color: colors.textPrimary, textAlign: 'center', marginBottom: Spacing.md },
  otpSub: { fontSize: FontSize.md, color: colors.textSecondary, textAlign: 'center', marginBottom: Spacing['4xl'], paddingHorizontal: Spacing.screenH },
  otpDisplayBox: {
    backgroundColor: colors.primaryBg,
    borderRadius: BorderRadius.lg,
    padding: Spacing['4xl'],
    alignItems: 'center',
    borderWidth: 1,
    borderColor: ExtendedColors.primaryBorder,
  },
  otpDisplayLabel: { fontSize: FontSize.base, fontWeight: FontWeight.semibold, color: ExtendedColors.primaryTextDeep, marginBottom: Spacing.lg },
  otpDisplayCode: { fontSize: FontSize['12xl'], fontWeight: FontWeight.extrabold, color: colors.primary, letterSpacing: 12 },
  otpLoadingBox: {
    backgroundColor: colors.screenBg,
    borderRadius: BorderRadius.lg,
    padding: Spacing['4xl'],
    alignItems: 'center',
    gap: Spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  otpLoadingText: { fontSize: FontSize.base, color: colors.textSecondary, fontWeight: FontWeight.medium },
  waitingHint: { paddingVertical: Spacing['2xl'], alignItems: 'center' },
  waitOwnerBox: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing['5xl'],
    paddingHorizontal: Spacing['4xl'],
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  waitOwnerIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing['2xl'],
  },
  waitOwnerTitle: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: Spacing.md,
  },
  waitOwnerSub: {
    fontSize: FontSize.base,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: Spacing['2xl'],
  },
  waitOwnerCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: BorderRadius.circleXl,
    paddingHorizontal: Spacing['3xl'],
    paddingVertical: Spacing.lg,
    marginBottom: Spacing['2xl'],
  },
  waitOwnerCallText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.primary,
  },
  waitOwnerStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: colors.primaryBg,
    paddingHorizontal: Spacing['2xl'],
    paddingVertical: Spacing.lg,
    borderRadius: BorderRadius.circleXl,
  },
  waitOwnerStatusText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.primary,
  },
  waitingHintText: { fontSize: FontSize.md, color: colors.textSecondary, fontWeight: FontWeight.medium },

  activeCard: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  activeHeader: {
    backgroundColor: colors.successBg,
    padding: Spacing['3xl'],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
  },
  dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.success },
  dotLeaving: { backgroundColor: colors.warning },
  leavingBanner: {
    backgroundColor: colors.warningBgAlt,
    borderRadius: BorderRadius.md,
    padding: Spacing['2xl'],
    marginBottom: Spacing.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.warning,
  },
  leavingBannerText: { fontSize: FontSize.base, color: ExtendedColors.warningAmber, lineHeight: 19 },
  activeTitle: { color: colors.success, fontWeight: FontWeight.extrabold, fontSize: FontSize.md, letterSpacing: 0.5 },
  activeBody: { padding: Spacing.screenH },
  activeLabel: { fontSize: FontSize.sm, color: colors.textMuted, fontWeight: FontWeight.bold },
  activeVal: { fontSize: FontSize.xl, color: colors.textPrimary, fontWeight: FontWeight.semibold, marginTop: Spacing.xs },

  contactRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.surfaceBg,
  },
  contactBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing['3xl'],
    gap: Spacing.md,
    borderRightWidth: 1,
    borderRightColor: colors.surfaceBg,
  },
  contactBtnText: { color: colors.textPrimary, fontWeight: FontWeight.semibold, fontSize: FontSize.md },

  helpSection: { marginTop: Spacing.screenH },
  helpLabel: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: Spacing.md },
  helpCard: { backgroundColor: colors.white, borderRadius: BorderRadius.lg, borderWidth: 1, borderColor: colors.border, overflow: 'hidden' },
  helpRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: Spacing['2xl'], paddingHorizontal: Spacing.screenH },
  helpDivider: { height: 1, backgroundColor: colors.surfaceBg, marginHorizontal: Spacing.screenH },
  helpRowLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  helpRowText: { fontSize: FontSize.md, color: colors.textPrimary, fontWeight: FontWeight.semibold },
  helpRowSub: { fontSize: FontSize.sm, color: colors.textMuted, marginTop: 1 },
  helpRowArrow: { fontSize: FontSize['3xl'], color: colors.textMuted, fontWeight: FontWeight.normal },

  footer: { padding: Spacing.screenH, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border },
  btnPrimary: { backgroundColor: colors.primary, borderRadius: BorderRadius.button, paddingVertical: Spacing['3xl'], alignItems: 'center' },
  btnPrimaryText: { color: colors.white, fontSize: FontSize.xl, fontWeight: FontWeight.bold },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: colors.white, borderTopLeftRadius: BorderRadius.xl, borderTopRightRadius: BorderRadius.xl, padding: Spacing['3xl'], paddingBottom: 36, maxHeight: '88%' },
  contextCard: { backgroundColor: colors.screenBg, borderRadius: BorderRadius.md, borderWidth: 1, borderColor: colors.border, padding: Spacing.xl, marginBottom: Spacing['3xl'] },
  contextRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 3 },
  contextLabel: { fontSize: FontSize.sm, color: colors.textMuted, fontWeight: FontWeight.medium },
  contextVal: { fontSize: FontSize.sm, color: colors.textPrimary, fontWeight: FontWeight.semibold, flexShrink: 1, marginLeft: Spacing.lg, textAlign: 'right' },
  modalHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.borderMuted, alignSelf: 'center', marginBottom: Spacing['2xl'] },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md },
  modalTitle: { fontSize: FontSize['2xl'], fontWeight: FontWeight.bold, color: colors.textPrimary },
  modalSub: { fontSize: FontSize.base, color: colors.textSecondary, marginBottom: Spacing['3xl'], lineHeight: 19 },
  fieldLabel: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: colors.textSecondary, marginBottom: Spacing.lg, textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  reasonRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: Spacing.lg, paddingVertical: Spacing.lg, paddingHorizontal: Spacing.xl, borderRadius: BorderRadius.md, marginBottom: Spacing.sm, backgroundColor: colors.screenBg, borderWidth: 1, borderColor: colors.border },
  reasonRowActive: { backgroundColor: colors.primaryBg, borderColor: colors.primary },
  radioOuter: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: colors.border, alignItems: 'center' as const, justifyContent: 'center' as const },
  radioOuterActive: { borderColor: colors.primary },
  radioInner: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.primary },
  reasonText: { fontSize: FontSize.base, color: colors.textBody, fontWeight: FontWeight.medium },
  reasonTextActive: { color: colors.primary, fontWeight: FontWeight.semibold },
  descInput: { backgroundColor: colors.screenBg, borderWidth: 1, borderColor: colors.border, borderRadius: BorderRadius.lg, padding: Spacing.xl, fontSize: FontSize.base, color: colors.textPrimary, minHeight: 80, marginBottom: Spacing['3xl'] },
  submitBtn: { backgroundColor: colors.error, borderRadius: BorderRadius.button, paddingVertical: Spacing['3xl'], alignItems: 'center' as const },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: colors.white, fontSize: FontSize.lg, fontWeight: FontWeight.bold },

  enRouteBanner: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.lg,
    backgroundColor: colors.infoBg, borderRadius: BorderRadius.lg, padding: Spacing['3xl'],
  },
  enRouteBannerEmoji: { fontSize: 28 },
  enRouteBannerTitle: { fontSize: FontSize.lg, fontWeight: FontWeight.bold, color: colors.textPrimary },
  enRouteBannerSub: { fontSize: FontSize.sm, color: colors.textSecondary, marginTop: 2, lineHeight: 17 },
  enRouteSection: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: colors.textPrimary, marginBottom: Spacing.xl },
  enRouteRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingVertical: Spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.surfaceBg,
  },
  enRouteLabel: { fontSize: FontSize.base, color: colors.textSecondary, flex: 1 },
  enRouteValue: { fontSize: FontSize.base, fontWeight: FontWeight.semibold, color: colors.textPrimary, textAlign: 'right' },

  // Payment disclaimer card — the app never collects/verifies/holds money, so the
  // parker just sees what's due plus a clear "pay the owner directly" note.
  payInfoCard: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: Spacing.screenH,
  },
  payInfoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  payInfoLabel: { fontSize: FontSize.md, fontWeight: FontWeight.semibold, color: colors.textSecondary },
  payInfoAmount: { fontSize: FontSize.xl, fontWeight: FontWeight.extrabold, color: colors.primary },
  payInfoDivider: { height: 1, backgroundColor: colors.surfaceBg, marginVertical: Spacing.lg },
  payInfoDisclaimer: { fontSize: FontSize.sm, color: colors.textSecondary, lineHeight: 19 },
  // UPI app icons — tap to open GPay/PhonePe/Paytm/BHIM pre-filled to pay the owner.
  payNowLabel: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: colors.textSecondary, marginTop: Spacing.lg, marginBottom: Spacing.md },
  upiAppsRow: { flexDirection: 'row', justifyContent: 'space-between' },
  upiAppBtn: { alignItems: 'center', flex: 1 },
  upiAppIcon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginBottom: Spacing.xs },
  upiAppIconText: { fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, color: '#FFFFFF' },
  upiAppLogo: { width: 44, height: 44, borderRadius: 22, marginBottom: Spacing.xs },
  upiAppName: { fontSize: FontSize.xs, color: colors.textSecondary, fontWeight: FontWeight.medium },
});
