import { StyleSheet } from 'react-native';
import type { ColorsType } from '../../theme';
import { FontSize, FontWeight, BorderRadius, ExtendedColors } from '../../theme';

export const makeAddSpaceStyles = (colors: ColorsType) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  container: {
    flex: 1,
    backgroundColor: colors.screenBg,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  formCard: {
    marginBottom: 16,
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
  },
  stepTitle: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    marginBottom: 12,
  },
  formGroup: {
    marginBottom: 6,
  },
  label: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,
    marginBottom: 8,
    marginLeft: 4,

    letterSpacing: 0,
  },
  required: {
    color: colors.primary,
  },
  errorText: {
    fontSize: FontSize.sm,
    color: colors.errorAlt,
    marginTop: 6,
  },
  chipRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: BorderRadius.circleXl,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  chipText: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,
  },
  chipTextActive: {
    color: colors.primary,
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  amenityChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.screenBg,
  },
  amenityChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
  },
  amenityText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: colors.textSecondary,
  },
  amenityTextActive: {
    color: colors.primary,
  },
  capacityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: BorderRadius.lg,
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: colors.white,
    marginTop: 8,
  },
  capacityCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.circleXl,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  capacityCircleBtnDisabled: {
    borderColor: colors.border,
    backgroundColor: colors.screenBg,
  },
  capacityCircleBtnText: {
    fontSize: FontSize['3xl'],
    fontWeight: FontWeight.bold,
    color: colors.primary,
    lineHeight: 24,
  },
  capacityCircleBtnTextDisabled: {
    color: colors.borderMuted,
  },
  capacityCenter: {
    alignItems: 'center',
  },
  capacityCount: {
    fontSize: FontSize['6xl'],
    fontWeight: FontWeight.extrabold,
    color: colors.textPrimary,
    lineHeight: 32,
  },
  capacityUnit: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,
    marginTop: 2,
  },
  capacityHint: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    marginTop: 6,
    marginLeft: 2,
    fontWeight: FontWeight.medium,
  },
  locationSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: 14,
    height: 52,
    backgroundColor: colors.white,
    marginBottom: 12,
  },
  locationSearchInput: {
    flex: 1,
    fontSize: FontSize.lg,
    fontWeight: FontWeight.medium,
    color: colors.textPrimary,
    paddingVertical: 0,
  },
  locationSearchBtn: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    backgroundColor: colors.primary,
    borderRadius: BorderRadius.input,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 48,
  },
  locationSearchBtnText: {
    color: colors.white,
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
  },
  currentLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 11,
    marginBottom: 12,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: '#FFF1F6',
  },
  currentLocationBtnText: {
    color: colors.primary,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
  },
  mapContainer: {
    borderRadius: BorderRadius.md,
    overflow: 'hidden',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  // Explicit height — the LeafletMap WebView is flex:1 internally and would
  // collapse to 0 inside the height-less mapContainer without this.
  mapView: {
    height: 220,
    width: '100%',
  },
  mapHint: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: colors.screenBg,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceBg,
    alignItems: 'center',
  },
  mapHintText: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
  },
  uploadGrid: {
    flexDirection: 'row',
    gap: 16,
  },
  uploadBox: {
    flex: 1,
    height: 120,
    backgroundColor: colors.screenBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderStyle: 'dashed',
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadBoxActive: {
    borderColor: colors.success,
    backgroundColor: colors.successBg,
    borderStyle: 'solid',
  },
  uploadPreview: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.sm,
    marginBottom: 6,
  },
  uploadBoxText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,
    marginTop: 8,
    textAlign: 'center',
  },
  successContainer: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 40,
    alignItems: 'center',
    backgroundColor: colors.screenBg,
  },
  successIconWrap: {
    marginBottom: 24,
  },
  successIconOuter: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.successBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: ExtendedColors.greenBorderLight,
  },
  successTitle: {
    fontSize: FontSize['5xl'],
    fontWeight: FontWeight.extrabold,
    color: colors.textPrimary,
    marginBottom: 10,
    textAlign: 'center',
  },
  successSubtitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
    paddingHorizontal: 8,
  },
  successCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  successDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.screenBg,
  },
  successDetailLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.textMuted,

    letterSpacing: 0.3,
  },
  successDetailValue: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    maxWidth: '60%',
    textAlign: 'right',
  },
  successStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.warningBgAlt,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: BorderRadius.circleXl,
  },
  successStatusDot: {
    width: 6,
    height: 6,
    borderRadius: BorderRadius.indicator,
    backgroundColor: colors.warningAlt,
  },
  successStatusText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: ExtendedColors.warningAmber,
  },
  successInfoBox: {
    width: '100%',
    backgroundColor: colors.infoBg,
    borderRadius: BorderRadius.md,
    padding: 14,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: ExtendedColors.blueTint,
  },
  successInfoText: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.medium,
    color: ExtendedColors.blueDark,
    lineHeight: 20,
  },
  successPrimaryBtn: {
    width: '100%',
    backgroundColor: colors.primary,
    borderRadius: BorderRadius.lg,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  successPrimaryBtnText: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: colors.white,
  },
  successSecondaryBtn: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  successSecondaryBtnText: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,
  },
  summaryCard: {
    backgroundColor: colors.white,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
    borderWidth: 1,
    borderColor: colors.surfaceBg,
    marginBottom: 12,
  },
  summarySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  summarySectionIcon: {
    width: 24,
    height: 24,
    borderRadius: BorderRadius.sm,
    backgroundColor: colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summarySectionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.screenBg,
    gap: 12,
  },
  summaryRowLast: {
    marginBottom: 6,
  },
  summaryRowLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.textMuted,

    letterSpacing: 0.3,
    flexShrink: 0,
  },
  summaryRowValue: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.semibold,
    color: colors.textPrimary,
    textAlign: 'right',
    flexShrink: 1,
  },
  summaryBox: {
    backgroundColor: colors.screenBg,
    padding: 16,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 24,
  },
  summaryLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: colors.textSecondary,

    letterSpacing: 0,
  },
  summaryValue: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
    marginTop: 4,
  },
  consentGroup: {
    marginBottom: 16,
  },
  consentCheckbox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: BorderRadius.badge,
    borderWidth: 2,
    borderColor: colors.borderMuted,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    flexShrink: 0,
  },
  checkboxActive: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  consentText: {
    flex: 1,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    color: colors.textBody,
    lineHeight: 20,
  },
  headerBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.screenBg,
    borderRadius: BorderRadius.sm,
    minWidth: 60,
    alignItems: 'center',
  },
  headerBtnDisabled: {
    opacity: 0.6,
  },
  headerBtnText: {
    color: colors.primary,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.md,
  },
  dropdownWrapper: {
    position: 'relative',
  },
  dropdownChevron: {
    position: 'absolute',
    right: 14,
    top: 34,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: BorderRadius.xl,
    borderTopRightRadius: BorderRadius.xl,
    paddingBottom: 32,
    maxHeight: '70%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: BorderRadius.dot,
    backgroundColor: colors.border,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceBg,
  },
  modalTitle: {
    fontSize: FontSize['2xl'],
    fontWeight: FontWeight.bold,
    color: colors.textPrimary,
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: BorderRadius.lg,
    backgroundColor: colors.surfaceBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.screenBg,
  },
  modalOptionActive: {
    backgroundColor: colors.primaryBg,
  },
  modalOptionText: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.medium,
    color: colors.textDark,
  },
  modalOptionTextActive: {
    fontWeight: FontWeight.bold,
    color: colors.primary,
  },
  complianceBanner: {
    backgroundColor: ExtendedColors.warningYellow,
    borderRadius: BorderRadius.md,
    padding: 14,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: ExtendedColors.warningYellowBorder,
  },
  complianceTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: ExtendedColors.warningDark,
    marginBottom: 6,
  },
  complianceText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: ExtendedColors.warningDeep,
    lineHeight: 18,
  },
  documentGuidance: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: colors.textSecondary,
    marginBottom: 10,
    fontStyle: 'italic',
  },
  chipDisabled: {
    opacity: 0.4,
  },
  chipTextDisabled: {
    color: colors.borderMuted,
  },
  customTimeSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopColor: colors.surfaceBg,
  },
  customTimeLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: colors.textSecondary,

    letterSpacing: 0.4,
    marginBottom: 12,
  },
  customTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  customTimeField: {
    flex: 1,
  },
  customTimeFieldLabel: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semibold,
    color: colors.textMuted,

    letterSpacing: 0.3,
    marginBottom: 6,
  },
  customTimeInput: {
    height: 44,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: BorderRadius.input,
    paddingHorizontal: 12,
    fontSize: FontSize.md,
    fontWeight: FontWeight.medium,
    color: colors.textPrimary,
    backgroundColor: colors.white,
  },
  timeInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  amPmToggle: {
    flexDirection: 'row',
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  amPmBtn: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: colors.screenBg,
  },
  amPmBtnActive: {
    backgroundColor: colors.primary,
  },
  amPmText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: colors.textMuted,
  },
  amPmTextActive: {
    color: colors.white,
  },
  timeHintError: {
    fontSize: FontSize.nano,
    color: colors.errorAlt,
    fontWeight: FontWeight.medium,
    marginTop: 3,
  },
  customTimeDash: {
    marginTop: 18,
  },
  customTimeDashText: {
    fontSize: FontSize['2xl'],
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
  },
  customTimeConfirmBtn: {
    backgroundColor: colors.primary,
    borderRadius: BorderRadius.input,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 8,
  },
  customTimeConfirmBtnDisabled: {
    backgroundColor: colors.surfaceBg,
  },
  customTimeConfirmText: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: colors.white,
  },
  customTimeConfirmTextDisabled: {
    color: colors.textMuted,
  },
  openFrontageInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: ExtendedColors.warningYellow,
    borderRadius: BorderRadius.input,
    padding: 14,
    borderWidth: 1,
    borderColor: ExtendedColors.warningYellowBorder,
    marginTop: 4,
  },
  openFrontageIcon: {
    fontSize: FontSize['3xl'],
    marginTop: 1,
  },
  openFrontageTitle: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: ExtendedColors.warningDark,
    marginBottom: 4,
  },
  openFrontageDesc: {
    fontSize: FontSize.sm,
    color: ExtendedColors.warningDeep,
    lineHeight: 17,
    fontWeight: FontWeight.medium,
  },
  uploadTypeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: -8,
    marginBottom: 4,
    paddingHorizontal: 2,
  },
  uploadTypeLabel: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    fontWeight: FontWeight.semibold,
  },
  uploadTypeValue: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: ExtendedColors.activeBlueText,
  },
  docModalSubtitle: {
    fontSize: FontSize.sm,
    color: colors.textSecondary,
    fontWeight: FontWeight.medium,
    paddingHorizontal: 20,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceBg,
  },
  docUploadTypeHint: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    marginTop: 2,
  },
  requiredProofBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.screenBg,
  },
  requiredProofText: {
    flex: 1,
    fontSize: FontSize.md,
    fontWeight: FontWeight.semibold,
    color: colors.textDark,
    lineHeight: 20,
  },
  openFrontageWarning: {
    backgroundColor: colors.warningBgAlt,
    borderRadius: BorderRadius.input,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: ExtendedColors.warningYellowBorderAlt,
  },
  openFrontageWarningText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.medium,
    color: ExtendedColors.warningAmber,
    lineHeight: 18,
  },
  chooseFileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: BorderRadius.lg,
    borderStyle: 'dashed',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.primaryBg,
  },
  chooseFileBtnText: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: colors.primary,
  },
  chooseFileSubtext: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    marginTop: 1,
  },
  uploadedDocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.screenBg,
    borderRadius: BorderRadius.input,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  uploadedDocName: {
    flex: 1,
    fontSize: FontSize.base,
    fontWeight: FontWeight.medium,
    color: colors.textDark,
  },
  uploadDocHint: {
    fontSize: FontSize.sm,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    marginTop: 6,
    marginLeft: 2,
  },
  dropdownWrapperDisabled: {
    opacity: 0.5,
  },
  labelDisabled: {
    color: colors.borderMuted,
  },
  docHint: {
    fontSize: FontSize.xs,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    marginTop: -4,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  modalSubtitle: {
    fontSize: FontSize.sm,
    color: colors.primary,
    fontWeight: FontWeight.semibold,
    marginTop: 2,
  },
  uploadLocked: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: BorderRadius.md,
    borderStyle: 'dashed',
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: colors.screenBg,
  },
  uploadLockedText: {
    fontSize: FontSize.base,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    flex: 1,
    lineHeight: 18,
  },
  uploadBoxSubtext: {
    fontSize: FontSize.nano,
    color: colors.textMuted,
    fontWeight: FontWeight.medium,
    marginTop: 2,
  },
});
